#!/usr/bin/bash 
# Original mlnx_bf_configure script is located at /sbin/mlnx_bf_configure.orig
# Temporary script. Need to support same flow as /sbin/mlnx_bf_configure.orig

is_bf=`lspci | grep BlueField | wc -l`
if [ $is_bf -ne 1 ]; then
        exit 0
fi

info()
{
                logger -t $prog -i "INFO: $*"
}

error()
{
                logger -t $prog -i "ERR: $*"
}

set_eswitch_mode()
{
        pci_dev=$1
        mode=$2
        shift 2

        sudo devlink dev eswitch set pci/${pci_dev} mode ${mode}
       echo "devlink dev eswitch set pci/$pci_dev mode $mode"
        rc=$?
        if [ $rc -ne 0 ]; then
                error "Failed to configure ${mode} mode for ${pci_dev}"
        else
                info "Configured ${mode} mode for ${pci_dev}"
        fi

        return $rc
}

for dev in `lspci -nD -d 15b3: | grep 'a2d[26c]' | cut -d ' ' -f 1`
do
        set_eswitch_mode ${dev} switchdev
done